image:
  file: .gitpod.Dockerfile

tasks:
- name: Create kubeconfig file
  init: mkdir /home/gitpod/.kube && echo "$K8S_KUBECONFIG" | base64 -d > /home/gitpod/.kube/config
  command: echo "File /home/gitpod/.kube/config created"
