image:
  file: .gitpod.Dockerfile

tasks:
- name: Set OVHcloud API variables
  init: export OVH_ENDPOINT="ovh-eu" && export OVH_APPLICATION_KEY="$(echo $OVH_API_AK_b64|base64 -d)" && export OVH_APPLICATION_SECRET="$(echo $OVH_API_AS_b64|base64 -d)" && export OVH_CONSUMER_KEY="$(echo $OVH_API_CK_b64|base64 -d)"
  command: echo "OVHcloud API variables setted"

